### ISSUE TITLE
[question] Is it possible to publish versions for Scala 2.11

### ISSUE THREAD

**Issue by eshepelyuk** [jtownson/swakka#3]
Hello @jtownson is ti technically possible to publish both 2.11 and 2.12 based versions ?
Since I can see only `2.12` version [HERE](https://mvnrepository.com/artifact/net.jtownson/swakka)

**Comment by jtownson** [comment]
Hi @eshepelyuk. Yes, I'll take a look. Sorry not to get back to you sooner.

**Comment by jtownson** [comment]
Hi @eshepelyuk. Swakka does apparently work with 2.11 so I have add this to the build and pushed the 2.11 jar.
The version of swakka with this change is 0.53. As of writing, the jars are still finding their way into maven central from sonatype. When they get there, you will need:
```
<dependency>
  <groupId>net.jtownson</groupId>
  <artifactId>swakka_2.11</artifactId>
  <version>0.53</version>
</dependency>
```
or 

```
libraryDependencies += "net.jtownson" %% "swakka" % "0.53"
```
I'll close this ticket once the jars have been propagated, but let me know if you encounter any problems.

**Comment by eshepelyuk** [comment]
Hi, the artififacts are a

**Comment by eshepelyuk** [comment]
Thank you very much for the help.
Artifacts are available at `jcenter` and can be successfully fetched by our build scripts.
